### ISSUE TITLE
Has anyone noticed a breaking layout using chrome 62? 

### ISSUE THREAD

**Issue by nathanvda** [Turbo87/sidebar-v2#131] opened 2017-11-07 13:40 UTC
I am checking now how to fix it, if I switch off the `line-height: 40px` on the `ul > li > a`  (in the inspector) at least the sidebar render correctly in chrome. Now checking if these is a good cross-browser fix (and what would be). 

Not sure if this is a bug in google chrome (and how to report it) or there would be a better css alternative. It seams at least that for some reason google chrome 62 seems to be adding some invisible padding but setting explicit padding/margins to 0 does not help. Adding a `margin-top: -10px` does but incredibly wrong. 

For the record: my page rendered correctly in chrome 61 and IE and in chrome 62 it looks as follows:
![pasted image at 2017_11_06 11_56 am](https://user-images.githubusercontent.com/34460/32496437-8187edc4-c3c9-11e7-87ff-1f57fbf492f1.png)

**Comment by Turbo87** [comment] 2017-11-07 13:41
this is a duplicate of https://github.com/Turbo87/sidebar-v2/issues/126 and already resolved in the latest release

**Closed by Turbo87** 2017-11-07 13:41 UTC

**Comment by nathanvda** [comment] 2017-11-07 13:44
Awesome, sorry for the noise and thanks for the quick update :+1: :+1: :+1:
