### ISSUE TITLE
Stop scrolling to anchor tags

### ISSUE THREAD

**Issue by onurkose** [Turbo87/sidebar-v2#25] opened 2015-05-04 20:20 UTC
Because events are not preventDefault'ed on _onClick assignment, page is scrolling to tab's title when you click the icons.

**Comment by Turbo87** [comment] 2015-07-30 07:08
I believe this is more or less a duplicate of #9. I guess using anchors for the tabs has not been such a great idea after all...

**Closed by Turbo87** 2015-07-30 07:08 UTC
